### ISSUE TITLE
Automate adding of "Contributors" to humans.txt

### ISSUE THREAD

**Issue by Charlotteis** [yourfirstpr/yourfirstpr.github.io#29]
Using the GitHub API.

**Comment by penman** [comment]
I'll have a go at this if you want. :)

**Comment by Charlotteis** [comment]
That'd be great!! @penman No rush or pressure, just do what you feel :) Thank you :)

**Comment by penman** [comment]
I just implemented this using GitHub web hooks.

<img width="352" alt="screen shot 2015-12-17 at 19 02 00" src="https://cloud.githubusercontent.com/assets/2768870/11878993/ae74c392-a4f0-11e5-8a85-f5008543e5ef.png">

This, from [GitHub's documentation](https://developer.github.com/v3/repos/#list-contributors), is a problem, though:

> Contributors data is cached for performance reasons. This endpoint may return information that is a few hours old.

Using the webhook approach, the contributors are checked immediately when a commit is created, so new contributors don't show up.

Because of this, it's probably better to just set up a script with a cron job every hour or so. I'll change my code to do that now.

**Comment by penman** [comment]
@Charlotteis ready! I just pushed [some code that does this](https://github.com/penman/humans). Do you have a server you can run it on?

**Comment by Charlotteis** [comment]
I don't! But I will be sorting out some hosting over the next week or two. This is awesome, thank you. :D

**Comment by penman** [comment]
That's good. Let me know if you need any help when you're setting it up. :)

**Comment by penman** [comment]
See #20 — there's a WAY easier way to do this that's completely automatic.
All that's needed is for the PR to be merged.
