### ISSUE TITLE
Create a build script for CSS minification

### ISSUE THREAD

**Issue by Charlotteis** [yourfirstpr/yourfirstpr.github.io#4]
This is not high priority, our CSS is unlikely to be big. This is just an opportunity for someone to try and get css minification working :)

1. Investigate and learn about CSS minification
2. Incorporate CSS minification through the use of a build script (such as through the use of NPM)

**Comment by BPScott** [comment]
Alternative idea (he says sliding in, not knowing what you've got planned): I'm assuming this is going to be a static site built onto GitHub pages as you've got a gh-pages branch.

In order to avoid complicating the build and deployment process, GH Pages supports pushing the source of a [Jekyll](https://help.github.com/articles/using-jekyll-with-pages/) site to your pages branch, which it then automatically builds (thus saving us having a build step for css minification that we then have to push output in the repository). Jekyll conveniently [supports compiling scss to css](http://jekyllrb.com/docs/assets/), along with a few other handy things like using layouts for common headers and footers if we end up with many pages. Thus, could this issue be expanded to be something like:

1) Investigate [how to use Jeykll with github pages](https://help.github.com/articles/using-jekyll-with-pages/) and how to use [Jekyll in general](http://jekyllrb.com/docs/home/)
2) Add a `Gemfile` specifying all the package dependencies
3) Add a Jekyll `_config.yml` that [configures sass compilation](http://jekyllrb.com/docs/assets/)
4) Update the css files to be compiled into a single file named `styles.css`, and have `index.html` reference that single file.

For reference, here's another repository that follows this approach: https://github.com/BPScott/talk-the-step-after-styleguides

**Comment by Charlotteis** [comment]
Thank you @BPScott! I will certainly consider my options the first chance I get. Also, a great step by step so you get an official 🌟from me :)

**Comment by JayWIlsonJr** [comment]
I created a build script. When I try to commit it says I don't have permission. What did I do wrong?
Thanks.

**Comment by Charlotteis** [comment]
Hi @JayWIlsonJr! You won't have permission to directly commit to this repository.

What you'll need to do is make a pull request.
To do this you'll need to fork the repository (the button that says 'Fork' at the top right of the page for this project), download your forked version to your computer and make your code changes there. You then commit your changes and can visit this project and click to make a pull request which will fetch your changes.

These articles should help:
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/using-pull-requests/

I hope this helps, thank you for your hard work :)

**Comment by JayWIlsonJr** [comment]
Thanks!

**Comment by matheussampaio** [comment]
Hi, can I make a PR for this issue?

**Comment by Charlotteis** [comment]
Hi @matheussampaio. I have an update on this issue.

@andeersg has made a Pull Request to change the way that the website is built. I will be reviewing this work as soon and hope to merge it. Then, the scope of this issue will change to do CSS minification under the guise of jekyll compilation. 

Which means @JayWIlsonJr that, though your work is *awesome*, it will become incompatible with the new way of working on the yourfirstpr website. I will keep your Pull Request open for now, but it is likely I will close it once the jekyll work is reviewed and merged.

I will keep everyone updated as much as possible and appreciate all the work that you are putting into this. I can only apologise that it is taking me so long to get to everyone, but know that it is one of my priorities.

Have a fantastic day!

☀️

**Comment by Charlotteis** [comment]
Closing because our new Jekyll build negates the need for a CSS Build Script. Thank you for everyone who got involved, particularly to @JayWIlsonJr who did some great and cool code.

:sparkling_heart:

**Comment by JayWIlsonJr** [comment]
Thanks for your kind words. Made my day. :smiley_cat:

**Comment by Charlotteis** [comment]
:D
